_commit: v1.15.7
_src_path: https://github.com/ff-fab/tmpl_python_project_kickstart
author_email: mail@fabiankoerner.com
author_name: Fabian Koerner
beads_prefix: cos
codecov: true
coverage_threshold: 80
description: an opinionated Python framework for building IoT-to-MQTT bridge applications
docker_publish: false
docs_style: dita
github_org: ff-fab
include_sbom: true
init_git_on_copy: true
license: MIT
module_name: cosalette
project_name: cosalette
release_please: true
repo_name: cosalette
robot_framework: false
surge_token: false
