"""Registration types and helper functions for the cosalette App."""

from cosalette._registration._model import (
    _UNSET,
    CommandRegistration,
    CronSpec,
    DeviceRegistration,
    EnabledSpec,
    IntervalSpec,
    LifespanFunc,
    NameSpec,
    RegistryType,
    TelemetryRegistration,
    TimeoutSpec,
    _AnyRegistration,
    _call_init,
    _CommandRegistration,
    _DeviceRegistration,
    _noop_lifespan,
    _ReactorRegistration,
    _StreamRegistration,
    _TelemetryRegistration,
    _Unset,
    _validate_init,
)
from cosalette._registration._shared import (
    build_reactor_registration,
    parse_adapter_tuple,
    process_adapters_dict,
    validate_stream_signature,
)
from cosalette._registration._validation import (
    _INVALID_MQTT_CHARS,
    _check_root_and_mixing,
    _validate_regular_command,
    _validate_sub_dispatch_command,
    check_device_name,
    colliding_names,
    validate_mqtt_name,
    validate_name_unique,
    validate_single_root,
    warn_if_mixing,
)
from cosalette._runners._periodic import PeriodicRegistration

__all__ = [
    "CronSpec",
    "EnabledSpec",
    "IntervalSpec",
    "LifespanFunc",
    "NameSpec",
    "RegistryType",
    "TimeoutSpec",
    "_AnyRegistration",
    "_CommandRegistration",
    "_DeviceRegistration",
    "_ReactorRegistration",
    "_StreamRegistration",
    "_TelemetryRegistration",
    "_UNSET",
    "_Unset",
    "_call_init",
    "_noop_lifespan",
    "_validate_init",
    "_INVALID_MQTT_CHARS",
    "_check_root_and_mixing",
    "_validate_regular_command",
    "_validate_sub_dispatch_command",
    "build_reactor_registration",
    "check_device_name",
    "colliding_names",
    "parse_adapter_tuple",
    "process_adapters_dict",
    "validate_mqtt_name",
    "validate_name_unique",
    "validate_single_root",
    "validate_stream_signature",
    "warn_if_mixing",
    # Public type aliases
    "CommandRegistration",
    "DeviceRegistration",
    "PeriodicRegistration",
    "TelemetryRegistration",
]
