"""Registration types and helper functions for the cosalette App."""

from cosalette._registration._model import (
    CronSpec,
    EnabledSpec,
    IntervalSpec,
    LifespanFunc,
    NameSpec,
    RegistryType,
    _AnyRegistration,
    _call_init,
    _CommandRegistration,
    _DeviceRegistration,
    _noop_lifespan,
    _StreamRegistration,
    _TelemetryRegistration,
    _validate_init,
)
from cosalette._registration._validation import (
    _INVALID_MQTT_CHARS,
    _check_root_and_mixing,
    _validate_regular_command,
    _validate_sub_dispatch_command,
    check_device_name,
    colliding_names,
    validate_mqtt_name,
    validate_name_unique,
    validate_single_root,
    warn_if_mixing,
)

__all__ = [
    "CronSpec",
    "EnabledSpec",
    "IntervalSpec",
    "LifespanFunc",
    "NameSpec",
    "RegistryType",
    "_AnyRegistration",
    "_CommandRegistration",
    "_DeviceRegistration",
    "_StreamRegistration",
    "_TelemetryRegistration",
    "_call_init",
    "_noop_lifespan",
    "_validate_init",
    "_INVALID_MQTT_CHARS",
    "_check_root_and_mixing",
    "_validate_regular_command",
    "_validate_sub_dispatch_command",
    "check_device_name",
    "colliding_names",
    "validate_mqtt_name",
    "validate_name_unique",
    "validate_single_root",
    "warn_if_mixing",
]
