"""ACL generation for MQTT brokers from AsyncAPI schemas.

Generates broker-specific ACL configurations by extracting channel topics and
their directions from schema registries.

See Also:
    ADR-033 — MQTT schema enforcement.
"""

from __future__ import annotations

import xml.etree.ElementTree as ET
from collections.abc import Callable
from dataclasses import dataclass

from cosalette._schema import SchemaRegistry


@dataclass(frozen=True, slots=True)
class AclPrincipal:
    """A principal (user/client) with topic permissions."""

    name: str
    publish_topics: tuple[str, ...]
    subscribe_topics: tuple[str, ...]


def derive_acl_principals(
    registry: SchemaRegistry,
    app_prefix: str | None = None,
) -> list[AclPrincipal]:
    """Create ACL principals from schema registry.

    Creates 3 types of principals:
    1. **deploy** — readwrite on ALL topics (wildcard #). Admin/deployment.
    2. **Per-app principals** — For each app found in channels:
       - Publish: "send" direction channels + framework topics
       - Subscribe: "receive" direction channels + schema updates
    3. **monitor** — Subscribe-only on status/error/availability topics

    Args:
        registry: The schema registry to extract channels from.
        app_prefix: If provided, only create principals for this app.

    Returns:
        List of ACL principals.
    """
    principals = []

    # 1. Deploy principal - always has wildcard access
    principals.append(
        AclPrincipal(
            name="deploy",
            publish_topics=("#",),
            subscribe_topics=("#",),
        )
    )

    # 2. Per-app principals
    app_names = {app_prefix} if app_prefix else registry.all_app_names()

    for app_name in app_names:
        publish_topics = []
        subscribe_topics = []

        # Framework topics that every app can publish
        framework_publish = [
            f"{app_name}/status",
            f"{app_name}/error",
            f"{app_name}/schema/status",
            f"{app_name}/_meta/registry",
            f"{app_name}/+/availability",
            f"{app_name}/+/error",
        ]
        publish_topics.extend(framework_publish)

        # Framework topics that every app subscribes to
        subscribe_topics.append("cosalette/schema/update")

        # Extract topics from operations for this app's channels
        for operation in registry.operations.values():
            # Find the channel this operation references
            channel = None
            for ch in registry.channels.values():
                if (operation.channel_ref == ch.address or
                    operation.channel_ref.endswith(ch.address)):
                    channel = ch
                    break

            if not channel:
                continue

            # Skip if channel is not for this app (unless scoped to all_apps)
            if (
                channel.app_name != app_name
                and channel.scope != "all_apps"
            ):
                continue

            if operation.action == "send":
                # App sends on this channel
                publish_topics.append(channel.address)
            elif operation.action == "receive":
                # App receives on this channel
                # Use wildcard pattern for command topics (e.g., app/+/set)
                if "{deviceName}" in channel.address:
                    wildcard_address = channel.address.replace("{deviceName}", "+")
                    subscribe_topics.append(wildcard_address)
                else:
                    subscribe_topics.append(channel.address)

        principals.append(
            AclPrincipal(
                name=app_name,
                publish_topics=tuple(sorted(set(publish_topics))),
                subscribe_topics=tuple(sorted(set(subscribe_topics))),
            )
        )

    # 3. Monitor principal - subscribe-only
    monitor_topics = [
        "+/schema/status",
        "+/status",
        "+/error",
        "+/+/error",
        "+/+/availability",
    ]
    
    principals.append(
        AclPrincipal(
            name="monitor",
            publish_topics=(),
            subscribe_topics=tuple(monitor_topics),
        )
    )

    return principals


def format_mosquitto(principals: list[AclPrincipal]) -> str:
    """Format principals as Mosquitto ACL file."""
    lines = [
        "# Generated by cosalette schema acl",
        "# Broker: Mosquitto",
        "",
    ]

    for principal in principals:
        lines.append(f"user {principal.name}")
        
        # Handle deploy special case with readwrite
        if principal.name == "deploy" and "#" in principal.publish_topics:
            lines.append("topic readwrite #")
        else:
            # Write permissions
            for topic in principal.publish_topics:
                lines.append(f"topic write {topic}")
            
            # Read permissions  
            for topic in principal.subscribe_topics:
                lines.append(f"topic read {topic}")
        
        lines.append("")

    return "\n".join(lines)


def format_emqx(principals: list[AclPrincipal]) -> str:
    """Format principals as EMQX Erlang ACL rules."""
    lines = [
        "%% Generated by cosalette schema acl",
        "%% Broker: EMQX",
        "",
    ]

    for principal in principals:
        name = principal.name

        # Handle deploy special case
        if name == "deploy" and "#" in principal.publish_topics:
            lines.append(f'{{allow, {{user, "{name}"}}, all, ["#"]}}.')
        else:
            # Publish permissions
            if principal.publish_topics:
                topics_str = ', '.join(
                    f'"{topic}"' for topic in principal.publish_topics
                )
                lines.append(f'{{allow, {{user, "{name}"}}, publish, [{topics_str}]}}.') 

            # Subscribe permissions
            if principal.subscribe_topics:
                topics_str = ', '.join(
                    f'"{topic}"' for topic in principal.subscribe_topics
                )
                lines.append(f'{{allow, {{user, "{name}"}}, subscribe, [{topics_str}]}}.') 

    lines.extend(["", "{deny, all}."])
    return "\n".join(lines)


def format_hivemq(principals: list[AclPrincipal]) -> str:
    """Format principals as HiveMQ XML configuration."""

    # Create root element
    root = ET.Element("file-rbac")
    root.insert(0, ET.Comment(" Generated by cosalette schema acl "))
    root.insert(1, ET.Comment(" Broker: HiveMQ "))

    # Users section
    users_elem = ET.SubElement(root, "users")

    # Roles section
    roles_elem = ET.SubElement(root, "roles")

    for principal in principals:
        # User element
        user_elem = ET.SubElement(users_elem, "user")
        name_elem = ET.SubElement(user_elem, "name")
        name_elem.text = principal.name

        roles_elem_user = ET.SubElement(user_elem, "roles")
        id_elem = ET.SubElement(roles_elem_user, "id")
        id_elem.text = principal.name

        # Role element
        role_elem = ET.SubElement(roles_elem, "role")
        role_id_elem = ET.SubElement(role_elem, "id")
        role_id_elem.text = principal.name

        permissions_elem = ET.SubElement(role_elem, "permissions")

        # Handle deploy special case
        if principal.name == "deploy" and "#" in principal.publish_topics:
            perm_elem = ET.SubElement(permissions_elem, "permission")
            topic_elem = ET.SubElement(perm_elem, "topic")
            topic_elem.text = "#"
        else:
            # Publish permissions
            for topic in principal.publish_topics:
                perm_elem = ET.SubElement(permissions_elem, "permission")
                topic_elem = ET.SubElement(perm_elem, "topic")
                topic_elem.text = topic
                activity_elem = ET.SubElement(perm_elem, "activity")
                activity_elem.text = "PUBLISH"

            # Subscribe permissions
            for topic in principal.subscribe_topics:
                perm_elem = ET.SubElement(permissions_elem, "permission")
                topic_elem = ET.SubElement(perm_elem, "topic")
                topic_elem.text = topic
                activity_elem = ET.SubElement(perm_elem, "activity")
                activity_elem.text = "SUBSCRIBE"

    # Convert to string with XML declaration
    return ET.tostring(root, encoding="unicode", xml_declaration=True)


def format_vernemq(principals: list[AclPrincipal]) -> str:
    """Format principals as VerneMQ ACL file (same as Mosquitto)."""
    lines = [
        "# Generated by cosalette schema acl",
        "# Broker: VerneMQ",
        "",
    ]

    # VerneMQ uses same format as Mosquitto
    mosquitto_content = format_mosquitto(principals)
    mosquitto_lines = mosquitto_content.split("\n")[3:]  # Skip header
    
    lines.extend(mosquitto_lines)
    return "\n".join(lines)


def format_nanomq(principals: list[AclPrincipal]) -> str:
    """Format principals as NanoMQ JSON-style rules."""
    lines = [
        "# Generated by cosalette schema acl",
        "# Broker: NanoMQ",
        "",
        "rules = [",
    ]

    for i, principal in enumerate(principals):
        name = principal.name
        
        # Handle deploy special case
        if name == "deploy" and "#" in principal.publish_topics:
            lines.append(f'    {{"permit": "allow", "username": "{name}", "action": "pubsub", "topics": ["#"]}},')
        else:
            # Publish permissions
            if principal.publish_topics:
                topics_list = list(principal.publish_topics)
                topics_str = str(topics_list).replace("'", '"')
                lines.append(f'    {{"permit": "allow", "username": "{name}", "action": "publish", "topics": {topics_str}}},')
            
            # Subscribe permissions  
            if principal.subscribe_topics:
                topics_list = list(principal.subscribe_topics)
                topics_str = str(topics_list).replace("'", '"')
                lines.append(f'    {{"permit": "allow", "username": "{name}", "action": "subscribe", "topics": {topics_str}}},')

    # Add deny all rule
    lines.append('    {"permit": "deny", "username": "#", "action": "pubsub", "topics": ["#"]}')
    lines.append("]")
    
    return "\n".join(lines)


# Registry of available formatters
FORMATTERS: dict[str, Callable[[list[AclPrincipal]], str]] = {
    "mosquitto": format_mosquitto,
    "emqx": format_emqx,
    "hivemq": format_hivemq,
    "vernemq": format_vernemq,
    "nanomq": format_nanomq,
}